Unit ICmd;

interface

const
  cmViewImage = 100;
  cmWriteImage = 101;
  cmPrepareImage = 102;
  cmEditProject = 105;
  cmSelectDrive = 110;
  cmReadBlocks = 111;
  cmVerifyBad = 112;
  cmAbout = 120;
  cmCalc = 121;


  cmCalcButton = 140;

  cmDetectOptions = 200;
  cmGeneralOptions = 201;
  cmReadOptions = 203;
  cmProjectOptions = 202;

  cmDetect = $300;
  cmSelect = $301;
  cmListSelectDrive = $400;

  cmSelectGeometry = 1000;

implementation

end.




